Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Controllers/AwardController.cs
using Epam.ListUsers.BLL.Logic;
using Epam.ListUsers.Entities;
using Epam.ListUsers.UI.WebInterface.Helpers;
using Epam.ListUsers.UI.WebInterface.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Epam.ListUsers.UI.WebInterface.Controllers
{
    public class AwardController : Controller
    {
        private UsersLogic _logic = new UsersLogic();
        private string PuthToDefaultImageForAwards = ConfigurationManager.AppSettings["PathForDefaultImageOfAwards"];
        
        // GET: Award
        [Authorize(Roles="admin")]
        public ActionResult Index()
        {
            var model = _logic.GetAllAwards().Select(a => Converters.ToAwardModel(a));
            return View(model);
        }

        // GET: Award/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(Guid id)
        {
            var award = _logic.GetAwardById(id);
            var model = Converters.ToAwardModel(award);
            model.Users = _logic.GetAllUsersWithAward(award).Select(u => u.Name).ToList();
            return View(model);
        }

        // GET: Award/Create
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Award/Create
        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(AwardModel model, HttpPostedFileBase uploadedFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    model.Id = Guid.NewGuid();
                    Award award = Converters.ToAwardForLogic(model);
                    _logic.AddAward(award);
                    if (uploadedFile != null)
                    {
                        _logic.SetImageOfAward(model.Id, uploadedFile);
                    }
                    
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Award/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Guid id)
        {

            Award award = _logic.GetAwardById(id);
            var model = Converters.ToAwardModel(award); 
            return View(model);
        }

        // POST: Award/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(AwardModel model, HttpPostedFileBase uploadedFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here
                    var award = Converters.ToAwardForLogic(model);
                    _logic.EditAward(award);
                    if (uploadedFile != null)
                    {
                        _logic.EditImageOfAward(model.Id, uploadedFile);
                    }
                    
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Award/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(Guid id)
        {
            var award = _logic.GetAwardById(id);
            _logic.RemoveAward(award);
            return RedirectToAction("Index");
        }

        public ActionResult Get(Guid? id)
        {
            if (id.HasValue)
            {
                return File(_logic.GetImageOfAward(id.Value), "image/jpeg");
            }
            else
            {
                var imageDefault = System.IO.File.ReadAllBytes(PuthToDefaultImageForAwards);
                return File(imageDefault, "image/jpeg");
            }
        }
    }
}

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Controllers/UserController.cs
using Epam.ListUsers.BLL.Logic;
using Epam.ListUsers.UI.WebInterface.Helpers;
using Epam.ListUsers.UI.WebInterface.Models;
using Epam.ListUsers.Entities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Configuration;

namespace Epam.ListUsers.UI.WebInterface.Controllers
{
    public class UserController : Controller
    {
        private UsersLogic _logic = new UsersLogic();
        private string PuthToDefaultImageForUsers = ConfigurationManager.AppSettings["PathForDefaultImageOfUsers"];

        // GET: User
        public ActionResult Index()
        {
            var model = _logic.GetAllUsers().Select(u => Converters.ToUserModelForDetails(u));
            return View(model);
        }

        // GET: User/Details/5
        [Authorize(Roles = "user")]    
        public ActionResult Details(Guid id)
        {
            var model = Converters.ToUserModelForDetails(_logic.GetUserById(id));
            return View(model);
        }

        // GET: User/Create
        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(UserModelForCreate model, HttpPostedFileBase uploadedFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    model.Id = Guid.NewGuid();
                    User user = Converters.ToUserForLogic(model);
                    _logic.AddUser(user);
                    if (uploadedFile != null)
                    {
                        _logic.SetImageOfUser(model.Id, uploadedFile);
                    }
                    
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            else 
            {
                return View(model);
            }
        }

        // GET: User/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Guid id)
        {
            User user = _logic.GetUserById(id);
            var model = Converters.ToUserModelForEdit(user);
            
            return View(model);
        }

        // POST: User/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(UserModelForEdit model, HttpPostedFileBase uploadedFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here
                    var user = Converters.ToUserForLogic(model);
                    _logic.EditUser(user);
                    if (uploadedFile != null)
                    {
                        _logic.EditImageOfUser(model.Id, uploadedFile);
                    }
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(model);
                }
            }
            else 
            {
                return View(model);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult DetailsAward(Guid idUser, Guid idAward)
        {
            var award = _logic.GetAwardById(idAward);
            var user = _logic.GetUserById(idUser);
            var model = Converters.ToAwardModelForDetails(award, user);
            return View(model);
        }

         //GET: User/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult ReAward(Guid idUser, Guid idAward)
        {
            var award = _logic.GetAwardById(idAward);
            var user = _logic.GetUserById(idUser);
            _logic.ReAward(user, award);
            return RedirectToAction("Edit", new { id = idUser });
        }

        // GET: User/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(Guid id)
        {
            if (ModelState.IsValid) 
            {
                try
                {
                    // TODO: Add delete logic here
                    var user = _logic.GetUserById(id);
                    _logic.RemoveUser(user);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
        
        [Authorize(Roles = "admin")]
        public ActionResult ToAward(Guid idUser)
        {
            var model = new AwardsModelForToAward();
            model.IdUser = idUser;
            model.Awards = _logic.GetAllAwards().Select(a => Converters.ToAwardModel(a)).ToList();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult ToAwardThisUser(Guid idUser, Guid idAward)
        {
            if (ModelState.IsValid)
            {
                var user = _logic.GetUserById(idUser);
                var award = _logic.GetAwardById(idAward);
                _logic.ToAward(user, award);
            }
            else
            {
                return View();
            }
            return RedirectToAction("Edit", new { id = idUser });
        }

        public ActionResult Get(Guid? id)
        {
            if (id.HasValue)
	        {
                
                return File(_logic.GetImageOfUser(id.Value), "image/jpeg");
	        }
            else
            {
                var imageDefault = System.IO.File.ReadAllBytes(PuthToDefaultImageForUsers);
                return File(imageDefault, "image/jpeg");
            }
        }
    }
}

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/Create.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.UserModelForCreate

@{
    ViewBag.Title = "Пользователи";
}

<h2>Создание нового пользователя</h2>

@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Заполните информацию о пользователе:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Фотография", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="show-image" class="picture" src="@Url.Action("Get")" />
                <input id="image" type="file" name="uploadedFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Фамилия Имя", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Дата рождения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/APP/UpdateImage.js"></script>
}

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/Delete.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.UserModelForDetails

@{
    ViewBag.Title = "Пользователи";
}

<h2>Удаление пользователя</h2>

<h3>Вы уверены, что хотите удалить данного пользователя?</h3>
<div>
    <h4>Пользователь</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>Фамилия Имя</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.Name</em></p>
        </dd>

        <dt>
            <span>Дата рождения</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.DateOfBirth</em></p>
        </dd>

        <dt>
            <span>Возраст</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.Age</em></p>
        </dd>

        @if (Model.Awards != null && Model.Awards.Count != 0)
        {
            <dt>
                <span>Награды</span>
            </dt>

            <dd>
                @foreach (var award in Model.Awards)
                {
                    <p class="data"><em>@award</em></p>
                }
            </dd>
        }
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/Details.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.UserModelForDetails

@{
    ViewBag.Title = "Пользователи";
}

<h2>Просмотр</h2>

<div>
    <h4>Пользователь</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <span>Фотография</span>
        </dt>

        <dd>
            <img class="picture" src="@Url.Action("Get", new { id = @Model.Id })" />
        </dd>

        <dt>
            <span>Фамилия Имя</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.Name</em></p>
        </dd>

        <dt>
            <span>Дата рождения</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.DateOfBirth</em></p>
        </dd>

        <dt>
            <span>Возраст</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.Age</em></p>
        </dd>

        @if (Model.Awards.Count != 0)
        {
            <dt>
                <span>Награды</span>
            </dt>

            <dd>
                @foreach (var award in Model.Awards)
                {
                    <p class="data"><em>@award</em></p>
                }
            </dd>
        }
    </dl>
</div>

<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/DetailsAward.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.AwardModelForDetailsAndReAward

@{
    ViewBag.Title = "Пользователи";
}

<h2>Просмотр награды пользователя @Model.NameUser</h2>

<div>
    <h4>Награда</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <span>Изображение</span>
        </dt>

        <dd>
            <img class="picture" src="@Url.Action("Get", "Award", new { id = @Model.IdAward })" />
        </dd>

        <dt>
            <span>Название награды</span>
        </dt>

        <dd>
            <p class="data"><em>@Model.Title</em></p>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Назад к пользователю", "Edit", new { id = Model.IdUser })
</p>

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/Edit.cshtml
@using Epam.ListUsers.UI.WebInterface.Models
@model UserModelForEdit

@{
    ViewBag.Title = "Пользователи";
}

<h2>Редактирование пользователя</h2>

@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Введите верные данные</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Фотография", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="show-image" class="picture" src="@Url.Action("Get", new { id = @Model.Id })" />
                <input id="image" type="file" name="uploadedFile" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Фамилия Имя", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Дата рождения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (Model.Awards.Count != 0)
        {
            <table class="table">
                <tr>
                    <th>
                        <span>Награды</span>
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Awards)
                {
                    <tr>
                        <td>
                            <p class="data"><em>@item.Title</em></p>
                        </td>
                        <td>
                            @Html.ActionLink("Посмотреть", "DetailsAward", new { idUser = Model.Id, idAward = item.Id }) |
                            <a class="delete" data-id-user="@Model.Id" data-id-award="@item.Id" data-message="Вы уверены что хотите удалить награду @item.Title у пользователя @Model.Name?">Удалить</a>
                        </td>
                    </tr>
                }
            </table>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Добавить награду", "ToAward", new { idUser = Model.Id }, new { @class = "btn btn-default" })
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

<form name="id" action="/User/ReAward" method="post">
    <input class="hidden" name="idUser" />
    <input class="hidden" name="idAward" />
</form>

@*@Html.Partial("ModalWindow")*@
@section scripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @*<script src="~/Scripts/APP/ControlModalWindow.js"></script>*@
    <script src="~/Scripts/APP/UpdateImage.js"></script>
}

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/Index.cshtml
@using Epam.ListUsers.UI.WebInterface.Models;
@model IEnumerable<UserModelForDetails>

@{
    ViewBag.Title = "Пользователи";
}

<h2>Пользователи</h2>
@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Создать нового пользователя", "Create")
    </p>
}

<table class="table">
    <tr>
        <th></th>
        <th>
            <span>Фамилия Имя</span>
        </th>
        <th>
            <span>Дата рождения</span>
        </th>
        <th>
            <span>Награды</span>
        </th>
        <th></th>
    </tr>
    
    @foreach (var item in Model) {
    <tr>
        <td>
            <img class="icon" src="@Url.Action("Get", new { id = @item.Id })" />
        </td>
        <td>
            <p class="data"><em>@item.Name</em></p>
        </td>
        <td>
            <p class="data"><em>@item.DateOfBirth</em></p>
        </td>
        <td>
            @foreach (var award in item.Awards)
            {
                <p><em>@award</em></p>
            }
        </td>
        
        <td>
    @if (User.Identity.IsAuthenticated && User.IsInRole("user"))
            {
        @Html.ActionLink("Посмотреть", "Details", new { id = item.Id })
            }
    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
	        {
            <span>|</span>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.Id })
            <span>|</span>
            <a class="delete" data-id="@item.Id" data-message="Вы уверены что хотите удалить пользователя @item.Name?">Удалить</a>
            }

    </td>
    </tr>
    }
    

</table>
<form name="id" action="User/Delete" method="post">
    <input class="hidden" name="id">
</form>


@Html.ActionLink("На главную страницу", "Index", "Home", null, new { @class = "btn btn-default" })

        @*@Html.Partial("ModalWindow")
            @section scripts{
                <script src="~/Scripts/APP/ControlModalWindow.js"></script>
            }*@

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/ModalWindow.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.UserModelForDetails

<div class="modal fade lu-modal" id="modal-message" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Подтверждение</h4>
            </div>
            <div class="modal-body">
                <h3>Вы уверены, что хотите удалить пользователя @Model.Name ?</h3>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Ok", "Delete", new { id = Model.Id }, new { @class = "btn btn-primary" })
                @*<button id="btnOk" class="btn btn-primary" type="button" data-dismiss="modal">Ok</button>*@
                <button id="btnCansel" class="btn btn-default" type="button" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/ModalWindowToDeleteUser.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.UserModelForDetails

<div class="modal fade lu-modal" id="modal-message" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Подтверждение</h4>
            </div>
            <div class="modal-body">
                <h3>Вы уверены, что хотите удалить пользователя @Model.Name ?</h3>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Ok", "Delete", new { id = Model.Id }, new { @class = "btn btn-primary" })
                @*<button id="btnOk" class="btn btn-primary" type="button" data-dismiss="modal">Ok</button>*@
                <button id="btnCansel" class="btn btn-default" type="button" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Epam.ListUsers/Epam.ListUsers.UI.WebInterface/Views/User/ToAward.cshtml
@model Epam.ListUsers.UI.WebInterface.Models.AwardsModelForToAward

@{
    ViewBag.Title = "Пользователи";
}

<h2>Выберете награду</h2>

<table class="table">
    <tr>
        <th></th>

        <th>
            <span>Награда</span>
        </th>

        <th></th>
    </tr>

@foreach (var item in Model.Awards)
{
    <tr>
        <td>
            <img class="icon" src="@Url.Action("Get", "Award", new { id = @item.Id })" />
        </td>
        <td>
            <p class="data"><em>@item.Title</em></p>
        </td>
        <td>
            @Html.ActionLink("Добавить", "ToAwardThisUser", new { idUser = Model.IdUser, idAward = item.Id })
        </td>
    </tr>
}
</table>
@Html.ActionLink("Назад к пользователю", "Edit", new { id = Model.IdUser })